name: Harry
favicon: null
layout_spectrum: 0.2837465866468847
typography_spectrum: 0.8308322909288108
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7590614254586399
  lightness: 0.3241931232623756
  saturation: 0.10321059403941035
  rhythmicContrast: 0.05493243969976902
purpose: []
